### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by whasf** [DarkstarProject/XiWeb#1]
After going through install dialog, I was presented with a blank screen for the main page. Turning PHP errors on I saw this:

`Parse error: syntax error, unexpected '.', expecting '&' or variable (T_VARIABLE) in C:\Inetpub\XiWeb\includes\functions.php on line 104`

**Comment by jdazzle** [comment]
It looks like there were some erroneous characters in that functions.php file.  Could you try replacing that file and trying again.  It's been updated in master branch with the fix hopefully.

**Comment by jdazzle** [comment]
Admittedly, I wasn't able to recreate the problem, but I did see the issue in the code.  I'm thinking it may possibly be a difference in our PHP settings.
