### ISSUE TITLE
There is no way to register an account on the webpage, and an error or error code will be prompted

### ISSUE THREAD

**Issue by ymchotmail** [DarkstarProject/XiWeb#4]
There is no way to register an account on the webpage, and an error or error code will be prompted Warning: file_get_contents(https://www.google.com/recaptcha/api/siteverify): failed to open stream: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. in C:\Inetpub\www\XiWeb\includes\Recaptcha\src\ReCaptcha\RequestMethod\Post.php on line 68

There was an error with the reCAPTCHA.

**Comment by takhlaq** [comment]
Darkstar Project and associated repos are no longer under development as of April 2020.
